"""add_tipo_paso_and_paso_siguiente_no

Revision ID: 4f290c3ca842
Revises: aae07fd3bad6
Create Date: 2026-06-15 00:25:26.084883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f290c3ca842'
down_revision: Union[str, None] = 'aae07fd3bad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paso', sa.Column('paso_siguiente_no', sa.String(length=10), nullable=True))
    op.add_column('paso', sa.Column('tipo_paso', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paso', 'tipo_paso')
    op.drop_column('paso', 'paso_siguiente_no')
    # ### end Alembic commands ###
