"""initial_schema

Revision ID: aae07fd3bad6
Revises: 
Create Date: 2026-06-14 14:40:01.242371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae07fd3bad6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categoria',
    sa.Column('id_categoria', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_categoria', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_categoria')
    )
    op.create_table('emergencia',
    sa.Column('id_emergencia', sa.String(length=10), nullable=False),
    sa.Column('nombre_emergencia', sa.String(length=100), nullable=False),
    sa.Column('descripcion_emergencia', sa.String(length=300), nullable=False),
    sa.Column('grupo_edad', sa.String(length=20), nullable=False),
    sa.Column('severidad', sa.String(length=20), nullable=False),
    sa.Column('etiqueta', sa.String(length=20), nullable=False),
    sa.Column('evaluacion_inicial', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id_emergencia'),
    sa.UniqueConstraint('nombre_emergencia')
    )
    op.create_table('permiso',
    sa.Column('id_permiso', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_permiso', sa.String(length=50), nullable=False),
    sa.Column('descripcion_permiso', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_permiso')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_rol', sa.String(length=50), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id_rol')
    )
    op.create_table('condicion',
    sa.Column('id_condicion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=True),
    sa.Column('nombre_condicion', sa.String(length=100), nullable=False),
    sa.Column('descripcion_condicion', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categoria.id_categoria'], ),
    sa.PrimaryKeyConstraint('id_condicion')
    )
    op.create_table('paso',
    sa.Column('id_paso', sa.String(length=10), nullable=False),
    sa.Column('id_emergencia', sa.String(length=10), nullable=True),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('instruccion', sa.Text(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('imagen', sa.String(length=300), nullable=True),
    sa.Column('paso_anterior', sa.String(length=10), nullable=True),
    sa.Column('paso_siguiente', sa.String(length=10), nullable=True),
    sa.Column('anexo', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['id_emergencia'], ['emergencia.id_emergencia'], ),
    sa.PrimaryKeyConstraint('id_paso')
    )
    op.create_table('rol_permiso',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_permiso', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_permiso'], ['permiso.id_permiso'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_rol', 'id_permiso')
    )
    op.create_table('usuario',
    sa.Column('cedula', sa.String(length=11), nullable=False),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('nombres', sa.String(length=255), nullable=False),
    sa.Column('apellidos', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('cedula'),
    sa.UniqueConstraint('email')
    )
    op.create_table('perfil_clinico',
    sa.Column('id_perfil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cedula', sa.String(length=11), nullable=True),
    sa.Column('genero', sa.String(length=12), nullable=False),
    sa.Column('tipo_sangre', sa.String(length=12), nullable=False),
    sa.Column('altura_cm', sa.Float(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['cedula'], ['usuario.cedula'], ),
    sa.PrimaryKeyConstraint('id_perfil'),
    sa.UniqueConstraint('cedula')
    )
    op.create_table('perfil_condicion',
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('id_condicion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_condicion'], ['condicion.id_condicion'], ),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfil_clinico.id_perfil'], ),
    sa.PrimaryKeyConstraint('id_perfil', 'id_condicion')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfil_condicion')
    op.drop_table('perfil_clinico')
    op.drop_table('usuario')
    op.drop_table('rol_permiso')
    op.drop_table('paso')
    op.drop_table('condicion')
    op.drop_table('rol')
    op.drop_table('permiso')
    op.drop_table('emergencia')
    op.drop_table('categoria')
    # ### end Alembic commands ###
